name: "CI - Nix"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: "Nix build on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        # os: ["ubuntu-24.04", "ubuntu-24.04-arm", "macos-13", "macos-14"]
        os: ["ubuntu-24.04", "ubuntu-24.04-arm"]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: gepetto
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check -L
      - run: nix develop --command python -c "import pinocchio; print(pinocchio.__version__)"
